server:
  # 服务器运行模式 release | debug
  # Server operating mode: release | debug
  run-mode: release
  # http-port
  # 服务器端口 - 格式为 -ip:port（绑定特定 IP）或 :port（绑定所有 IPs）
  # Server port - format: -ip:port (bind to a specific IP) or :port (bind to all IPs)
  http-port: :9000
  # 读取超时时间（秒），请求超时前等待的最大时间
  # Read timeout (seconds), maximum time to wait before request timeout
  read-timeout: 60
  # 写入超时时间（秒），写入超时前等待的最大时间
  # Write timeout (seconds), maximum time to wait before write timeout
  write-timeout: 60
  # 性能监控接口（私有 HTTP 服务器）
  # Performance monitoring interface (private HTTP server)
  private-http-listen: :9001

app:
  # 默认每页显示的项目数（分页）
  # Default number of items per page (pagination)
  default-page-size: 10
  # 最大每页允许的项目数（分页）
  # Maximum number of items allowed per page (pagination)
  max-page-size: 100
  # 应用操作的默认超时时间（秒）
  # Default timeout for application operations (seconds)
  default-context-timeout: 60
  # 临时文件存储路径
  # Temporary file storage path
  temp-path: storage/temp

user:
  # 是否开启注册功能
  # Whether to enable registration
  register-is-enable: true
  # 是否返回成功消息
  # Whether to return success messages
  is-return-sussess: false

log:
  # 日志级别
  # Log level
  level: debug
  # 日志文件路径
  # Log file path
  file: storage/logs/log.log
  # 是否为生产环境
  # Whether this is a production environment
  production: true

security:
  # 用于加密认证数据的密钥
  # Key for encrypting authentication data
  encryption_key: X-Auth-Token-API

# database
# 数据库配置
# Database configuration
database:
  type: sqlite
  path: storage/database/db.sqlite3
  table-prefix:
  auto-migrate: true

