// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/fast-note-sync-service/pkg/timex"

const TableNameAuthTokenLog = "auth_token_log"

// AuthTokenLog mapped from table <auth_token_log>
type AuthTokenLog struct {
	ID         int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	TokenID    int64      `gorm:"column:token_id;not null;index:idx_auth_token_log_token_id,priority:1;default:0" json:"tokenId" form:"tokenId"`
	UID        int64      `gorm:"column:uid;not null;index:idx_auth_token_log_uid,priority:1;default:0" json:"uid" form:"uid"`
	Path       string     `gorm:"column:path;not null;default:''" json:"path" form:"path"`
	Method     string     `gorm:"column:method;not null;default:''" json:"method" form:"method"`
	IP         string     `gorm:"column:ip;not null;default:''" json:"ip" form:"ip"`
	StatusCode int64      `gorm:"column:status_code;not null;default:0" json:"statusCode" form:"statusCode"`
	CreatedAt  timex.Time `gorm:"column:created_at;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
}

// TableName AuthTokenLog's table name
func (*AuthTokenLog) TableName() string {
	return TableNameAuthTokenLog
}
