// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/obsidian-better-sync-service/pkg/timex"

const TableNameNote = "note"

// Note mapped from table <note>
type Note struct {
	ID        int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	Vault     string     `gorm:"column:vault" json:"vault" form:"vault"`
	Action    string     `gorm:"column:action" json:"action" form:"action"`
	Path      string     `gorm:"column:path" json:"path" form:"path"`
	PathHash  string     `gorm:"column:path_hash" json:"pathHash" form:"pathHash"`
	Content   string     `gorm:"column:content" json:"content" form:"content"`
	Size      int64      `gorm:"column:size;not null" json:"size" form:"size"`
	IsDeleted int64      `gorm:"column:is_deleted;not null" json:"isDeleted" form:"isDeleted"`
	CreatedAt timex.Time `gorm:"column:created_at;type:datetime;autoCreateTime" json:"createdAt" form:"createdAt"`
	UpdatedAt timex.Time `gorm:"column:updated_at;type:datetime;autoUpdateTime" json:"updatedAt" form:"updatedAt"`
	DeletedAt timex.Time `gorm:"column:deleted_at;type:datetime;default:NULL" json:"deletedAt" form:"deletedAt"`
}

// TableName Note's table name
func (*Note) TableName() string {
	return TableNameNote
}
