// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "github.com/haierkeys/obsidian-better-sync-service/pkg/timex"

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	UID       int64      `gorm:"column:uid;primaryKey" json:"uid" type:"uid" form:"uid"`
	Email     string     `gorm:"column:email" json:"email" type:"email" form:"email"`
	Username  string     `gorm:"column:username" json:"username" type:"username" form:"username"`
	Password  string     `gorm:"column:password" json:"password" type:"password" form:"password"`
	Salt      string     `gorm:"column:salt" json:"salt" type:"salt" form:"salt"`
	Token     string     `gorm:"column:token" json:"token" type:"token" form:"token"`
	Avatar    string     `gorm:"column:avatar" json:"avatar" type:"avatar" form:"avatar"`
	IsDeleted int64      `gorm:"column:is_deleted" json:"isDeleted" type:"isDeleted" form:"isDeleted"`
	UpdatedAt timex.Time `gorm:"column:updated_at;type:datetime;default:NULL;autoUpdateTime:false" json:"updatedAt" type:"updatedAt" form:"updatedAt"`
	CreatedAt timex.Time `gorm:"column:created_at;type:datetime;default:NULL;autoUpdateTime:false" json:"createdAt" type:"createdAt" form:"createdAt"`
	DeletedAt timex.Time `gorm:"column:deleted_at;type:datetime;default:NULL;autoUpdateTime:false" json:"deletedAt" type:"deletedAt" form:"deletedAt"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
