// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/haierkeys/fast-note-sync-service/pkg/timex"
)

const TableNameUserShare = "user_share"

// UserShare mapped from table <user_share>
type UserShare struct {
	ID           int64      `gorm:"column:id;primaryKey" json:"id" form:"id"`
	UID          int64      `gorm:"column:uid;not null;default:0" json:"uid" form:"uid"`
	Res          string     `gorm:"column:res;not null;default:''" json:"res" form:"res"`
	Status       int64      `gorm:"column:status;type:INTEGER;default:0" json:"status" form:"status"`
	ViewCount    int64      `gorm:"column:view_count;type:INTEGER;default:0" json:"viewCount" form:"viewCount"`
	LastViewedAt time.Time  `gorm:"column:last_viewed_at;type:datetime" json:"lastViewedAt" form:"lastViewedAt"`
	ExpiresAt    time.Time  `gorm:"column:expires_at" json:"expiresAt" form:"expiresAt"`
	CreatedAt    timex.Time `gorm:"column:created_at;type:datetime;default:NULL;autoCreateTime:false" json:"createdAt" form:"createdAt"`
	UpdatedAt    timex.Time `gorm:"column:updated_at;type:datetime;default:NULL;autoUpdateTime:false" json:"updatedAt" form:"updatedAt"`
}

// TableName UserShare's table name
func (*UserShare) TableName() string {
	return TableNameUserShare
}
