// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:          db,
		File:        newFile(db, opts...),
		Folder:      newFolder(db, opts...),
		Note:        newNote(db, opts...),
		NoteHistory: newNoteHistory(db, opts...),
		NoteLink:    newNoteLink(db, opts...),
		Setting:     newSetting(db, opts...),
		Storage:     newStorage(db, opts...),
		User:        newUser(db, opts...),
		UserShare:   newUserShare(db, opts...),
		Vault:       newVault(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	File        file
	Folder      folder
	Note        note
	NoteHistory noteHistory
	NoteLink    noteLink
	Setting     setting
	Storage     storage
	User        user
	UserShare   userShare
	Vault       vault
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		File:        q.File.clone(db),
		Folder:      q.Folder.clone(db),
		Note:        q.Note.clone(db),
		NoteHistory: q.NoteHistory.clone(db),
		NoteLink:    q.NoteLink.clone(db),
		Setting:     q.Setting.clone(db),
		Storage:     q.Storage.clone(db),
		User:        q.User.clone(db),
		UserShare:   q.UserShare.clone(db),
		Vault:       q.Vault.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:          db,
		File:        q.File.replaceDB(db),
		Folder:      q.Folder.replaceDB(db),
		Note:        q.Note.replaceDB(db),
		NoteHistory: q.NoteHistory.replaceDB(db),
		NoteLink:    q.NoteLink.replaceDB(db),
		Setting:     q.Setting.replaceDB(db),
		Storage:     q.Storage.replaceDB(db),
		User:        q.User.replaceDB(db),
		UserShare:   q.UserShare.replaceDB(db),
		Vault:       q.Vault.replaceDB(db),
	}
}

type queryCtx struct {
	File        IFileDo
	Folder      IFolderDo
	Note        INoteDo
	NoteHistory INoteHistoryDo
	NoteLink    INoteLinkDo
	Setting     ISettingDo
	Storage     IStorageDo
	User        IUserDo
	UserShare   IUserShareDo
	Vault       IVaultDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		File:        q.File.WithContext(ctx),
		Folder:      q.Folder.WithContext(ctx),
		Note:        q.Note.WithContext(ctx),
		NoteHistory: q.NoteHistory.WithContext(ctx),
		NoteLink:    q.NoteLink.WithContext(ctx),
		Setting:     q.Setting.WithContext(ctx),
		Storage:     q.Storage.WithContext(ctx),
		User:        q.User.WithContext(ctx),
		UserShare:   q.UserShare.WithContext(ctx),
		Vault:       q.Vault.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
