package code

var (
	Failed                = NewError(0, lang{zh_cn: "失败", en: "Failed"})
	Success               = NewSuss(incr(1), lang{zh_cn: "成功", en: "Success"})
	SuccessCreate         = NewSuss(incr(1), lang{zh_cn: "创建成功", en: "Create Success"})
	SuccessUpdate         = NewSuss(incr(1), lang{zh_cn: "更新成功", en: "Update Success"})
	SuccessDelete         = NewSuss(incr(1), lang{zh_cn: "删除成功", en: "Delete Success"})
	SuccessPasswordUpdate = NewSuss(incr(1), lang{zh_cn: "密码修改成功", en: "Password Update Success"})
	SuccessNoUpdate       = NewSuss(incr(1), lang{zh_cn: "无更新", en: "No Update"})

	ErrorServerInternal       = NewError(500, lang{zh_cn: "服务器内部错误", en: "Server Internal Error"}, true)
	ErrorDBQuery              = NewError(501, lang{zh_cn: "数据库查询失败", en: "Database query failed"}, true)
	ErrorTooManyRequests      = NewError(503, lang{zh_cn: "请求过多", en: "Too Many Requests"}, true)
	ErrorNotFoundAPI          = NewError(504, lang{zh_cn: "找不到API", en: "Not Found API"}, true)
	ErrorInvalidParams        = NewError(505, lang{zh_cn: "参数验证失败", en: "Invalid Params"})
	ErrorInvalidAuthToken     = NewError(506, lang{zh_cn: "访问令牌效验失败", en: "Invalid Auth Token"})
	ErrorNotUserAuthToken     = NewError(507, lang{zh_cn: "尚未登录,请先登录", en: "Not logged in. Please log in first."})
	ErrorInvalidUserAuthToken = NewError(508, lang{zh_cn: "登录状态失效,请重新登录", en: "Session expired, please log in again."})
	ErrorInvalidToken         = NewError(509, lang{zh_cn: "您的访问缺少用户令牌", en: "Your access is missing a user token"})
	ErrorTokenExpired         = NewError(510, lang{zh_cn: "用户令牌已过期", en: "User token has expired"})

	ErrorUserRegister                = NewError(400, lang{zh_cn: "用户注册失败", en: "User registration failed"})
	ErrorUserOldPasswordFailed       = NewError(401, lang{zh_cn: "当前密码验证错误", en: "Current password verification error"})
	ErrorPasswordNotValid            = NewError(402, lang{zh_cn: "密码不符合规则", en: "Password does not meet the rules"})
	ErrorUserLoginPasswordFailed     = NewError(403, lang{zh_cn: "密码错误", en: "Password error"})
	ErrorMultiUserPublicAPIClosed    = NewError(404, lang{zh_cn: "多用户开放接口已经关闭,请联系管理员配置 config.user.is-user-enable 选项", en: "Multi-user open interface has been closed, please contact the administrator to configure the config.user.is-user-enable option"})
	ErrorUserRegisterIsDisable       = NewError(405, lang{zh_cn: "用户注册已关闭,请联系管理员配置 config.user.register-is-enable 选项", en: "User registration is closed, please contact the administrator to configure the config.user.register-is-enable option"})
	ErrorUserLoginFailed             = NewError(406, lang{zh_cn: "用户登录失败", en: "User login failed"})
	ErrorUserNotFound                = NewError(407, lang{zh_cn: "用户不存在", en: "Username does not exist"})
	ErrorUserAlreadyExists           = NewError(408, lang{zh_cn: "用户已经存在", en: "Username already exists"})
	ErrorUserEmailAlreadyExists      = NewError(409, lang{zh_cn: "用户邮箱已存在", en: "User email already exists"})
	ErrorUserUsernameNotValid        = NewError(410, lang{zh_cn: "用户名不符合规则,用户名长度为3-15位,只能包含字母、数字或下划线", en: "The username does not meet the rules, the username length is 3-15 digits, and can only contain letters, numbers or underscores"})
	ErrorUserPasswordNotMatch        = NewError(411, lang{zh_cn: "两次输入的密码不一致", en: "The two passwords entered are inconsistent"})
	ErrorInvalidCloudStorageType     = NewError(412, lang{zh_cn: "云存储类型无效", en: "Invalid cloud storage type"})
	ErrorInvalidStorageType          = NewError(413, lang{zh_cn: "存储类型无效", en: "Invalid storage type"})
	ErrorVaultNotFound               = NewError(414, lang{zh_cn: "笔记仓库不存在", en: "Note Vault does not exist"})
	ErrorVaultExist                  = NewError(415, lang{zh_cn: "笔记仓库已经存在", en: "Note Vault already exists"})
	ErrorFileDeleteFailed            = NewError(416, lang{zh_cn: "附件删除失败", en: "Delete file failed"})
	ErrorFileModifyOrCreateFailed    = NewError(417, lang{zh_cn: "附件修改或创建失败", en: "File modify or create failed"})
	ErrorFileContentModifyFailed     = NewError(418, lang{zh_cn: "修改文件内容失败", en: "Modify file content failed"})
	ErrorFileGetFailed               = NewError(419, lang{zh_cn: "获取文件失败", en: "Get file failed"})
	ErrorFileUploadSessionNotFound   = NewError(420, lang{zh_cn: "上传文件会话不存在", en: "Upload file session not found"})
	ErrorFileUploadFailed            = NewError(421, lang{zh_cn: "上传文件失败", en: "Upload file failed"})
	ErrorFileUploadCheckFailed       = NewError(422, lang{zh_cn: "上传文件失败检测失败", en: "File upload check failed"})
	ErrorFileListFailed              = NewError(423, lang{zh_cn: "文件列表获取失败", en: "File list get failed"})
	ErrorNoteDeleteFailed            = NewError(424, lang{zh_cn: "笔记删除失败", en: "Delete note failed"})
	ErrorNoteModifyOrCreateFailed    = NewError(425, lang{zh_cn: "笔记修改或创建失败", en: "Note modify or create failed"})
	ErrorNoteContentModifyFailed     = NewError(426, lang{zh_cn: "修改笔记内容失败", en: "Modify note content failed"})
	ErrorNoteGetFailed               = NewError(427, lang{zh_cn: "获取笔记失败", en: "Get note failed"})
	ErrorNoteNotFound                = NewError(428, lang{zh_cn: "笔记不存在", en: "Note does not exist"})
	ErrorNoteExist                   = NewError(429, lang{zh_cn: "笔记已经存在", en: "Note already exists"})
	ErrorRenameNoteTargetExist       = NewError(430, lang{zh_cn: "笔记重命名目标笔记已经存在", en: "Note rename target note already exists"})
	ErrorNoteSyncFailed              = NewError(431, lang{zh_cn: "同步笔记失败", en: "Sync note failed"})
	ErrorNoteUpdateCheckFailed       = NewError(432, lang{zh_cn: "笔记更新检查失败", en: "Note update check failed"})
	ErrorNoteListFailed              = NewError(433, lang{zh_cn: "笔记列表获取失败", en: "Note list get failed"})
	ErrorNoteRenameFailed            = NewError(434, lang{zh_cn: "笔记重命名失败", en: "Note rename failed"})
	ErrorSettingDeleteFailed         = NewError(435, lang{zh_cn: "配置删除失败", en: "Delete setting failed"})
	ErrorSettingModifyOrCreateFailed = NewError(436, lang{zh_cn: "配置修改或创建失败", en: "Setting modify or create failed"})
	ErrorSettingContentModifyFailed  = NewError(437, lang{zh_cn: "修改配置内容失败", en: "Modify setting content failed"})
	ErrorSettingGetFailed            = NewError(438, lang{zh_cn: "获取配置失败", en: "Get setting failed"})
	ErrorSettingNotFound             = NewError(439, lang{zh_cn: "配置不存在", en: "Setting does not exist"})
	ErrorSettingExist                = NewError(440, lang{zh_cn: "配置已经存在", en: "Setting already exists"})
	ErrorSettingSyncFailed           = NewError(441, lang{zh_cn: "同步配置失败", en: "Sync setting failed"})
	ErrorSettingUpdateCheckFailed    = NewError(442, lang{zh_cn: "配置更新检查失败", en: "Setting update check failed"})
	ErrorSettingListFailed           = NewError(443, lang{zh_cn: "配置列表获取失败", en: "Setting list get failed"})
	ErrorUserLocalFSDisabled         = NewError(444, lang{zh_cn: "用户本地文件系统已禁用", en: "User local file system is disabled"})
)
