package code

var (
	Failed                = NewError(0)
	Success               = NewSuss(1)
	SuccessCreate         = NewSuss(2)
	SuccessUpdate         = NewSuss(3)
	SuccessDelete         = NewSuss(4)
	SuccessPasswordUpdate = NewSuss(5)
	SuccessNoUpdate       = NewSuss(6)

	ErrorServerInternal       = NewError(300, true)
	ErrorDBQuery              = NewError(301, true)
	ErrorServerBusy           = NewError(302, true)
	ErrorTooManyRequests      = NewError(303, true)
	ErrorNotFoundAPI          = NewError(304, true)
	ErrorInvalidParams        = NewError(305)
	ErrorInvalidAuthToken     = NewError(306)
	ErrorNotUserAuthToken     = NewError(307)
	ErrorInvalidUserAuthToken = NewError(308)
	ErrorInvalidToken         = NewError(309)
	ErrorTokenExpired         = NewError(310)
	ErrorTokenGenerate        = NewError(311)

	// --- User Related (400-419) ---
	ErrorUserRegister            = NewError(400)
	ErrorUserLoginFailed         = NewError(401)
	ErrorUserLoginPasswordFailed = NewError(402)
	ErrorUserNotFound            = NewError(403)
	ErrorUserAlreadyExists       = NewError(404)
	ErrorUserEmailAlreadyExists  = NewError(405)
	ErrorUserUsernameNotValid    = NewError(406)
	ErrorPasswordNotValid        = NewError(407)
	ErrorUserOldPasswordFailed   = NewError(408)
	ErrorUserPasswordNotMatch    = NewError(409)
	ErrorUserRegisterIsDisable   = NewError(410)
	ErrorUserIsNotAdmin          = NewError(411)
	ErrorUserLocalFSDisabled     = NewError(412)

	// --- Vault Related (420-429) ---
	ErrorVaultNotFound           = NewError(420)
	ErrorVaultExist              = NewError(421)
	ErrorInvalidStorageType      = NewError(422)
	ErrorInvalidCloudStorageType = NewError(423)

	// --- Note Related (430-449) ---
	ErrorNoteNotFound             = NewError(430)
	ErrorNoteExist                = NewError(431)
	ErrorNoteGetFailed            = NewError(432)
	ErrorNoteModifyOrCreateFailed = NewError(433)
	ErrorNoteContentModifyFailed  = NewError(434)
	ErrorNoteDeleteFailed         = NewError(435)
	ErrorNoteListFailed           = NewError(436)
	ErrorNoteRenameFailed         = NewError(437)
	ErrorRenameNoteTargetExist    = NewError(438)
	ErrorNoteSyncFailed           = NewError(439)
	ErrorNoteUpdateCheckFailed    = NewError(440)
	ErrorNoteConflict             = NewError(441)
	ErrorNoMatchFound             = NewError(442)
	ErrorInvalidRegex             = NewError(443)
	ErrorInvalidPath              = NewError(444)
	ErrorFolderNotFound           = NewError(445)
	ErrorFolderExist              = NewError(446)

	// --- File/Attachment Related (450-464) ---
	ErrorFileNotFound              = NewError(450)
	ErrorFileGetFailed             = NewError(451)
	ErrorFileModifyOrCreateFailed  = NewError(452)
	ErrorFileContentModifyFailed   = NewError(453)
	ErrorFileDeleteFailed          = NewError(454)
	ErrorFileListFailed            = NewError(455)
	ErrorFileUploadFailed          = NewError(456)
	ErrorFileUploadCheckFailed     = NewError(457)
	ErrorFileUploadSessionNotFound = NewError(458)
	ErrorFileSaveFailed            = NewError(459)
	ErrorFileMoveFailed            = NewError(460)
	ErrorFileReadFailed            = NewError(461)

	// --- Setting Related (465-474) ---
	ErrorSettingNotFound             = NewError(465)
	ErrorSettingExist                = NewError(466)
	ErrorSettingGetFailed            = NewError(467)
	ErrorSettingModifyOrCreateFailed = NewError(468)
	ErrorSettingContentModifyFailed  = NewError(469)
	ErrorSettingDeleteFailed         = NewError(470)
	ErrorSettingListFailed           = NewError(471)
	ErrorSettingSyncFailed           = NewError(472)
	ErrorSettingUpdateCheckFailed    = NewError(473)
	ErrorConfigSaveFailed            = NewError(474)

	// --- Share Related (475-484) ---
	ErrorShareNotFound = NewError(475)
	ErrorShareExpired  = NewError(476)
	ErrorShareRevoked  = NewError(477)

	// --- Sync & History (485-499) ---
	ErrorSyncConflict         = NewError(485)
	ErrorHistoryNotFound      = NewError(486)
	ErrorHistoryRestoreFailed = NewError(487)
)
